// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Base62Helper is an autogenerated mock type for the Base62Helper type
type Base62Helper struct {
	mock.Mock
}

// Encode provides a mock function with given fields: data
func (_m *Base62Helper) Encode(data string) string {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewBase62Helper creates a new instance of Base62Helper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBase62Helper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Base62Helper {
	mock := &Base62Helper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
