// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/homework/lab/internal/models/entity"
	mock "github.com/stretchr/testify/mock"
)

// BookmarkRepository is an autogenerated mock type for the BookmarkRepository type
type BookmarkRepository struct {
	mock.Mock
}

// CreateBookmark provides a mock function with given fields: ctx, userId, url, description, code
func (_m *BookmarkRepository) CreateBookmark(ctx context.Context, userId string, url string, description string, code string) (*entity.Bookmark, error) {
	ret := _m.Called(ctx, userId, url, description, code)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookmark")
	}

	var r0 *entity.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*entity.Bookmark, error)); ok {
		return rf(ctx, userId, url, description, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *entity.Bookmark); ok {
		r0 = rf(ctx, userId, url, description, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, userId, url, description, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBookmark provides a mock function with given fields: ctx, userId, bookmarkId
func (_m *BookmarkRepository) DeleteBookmark(ctx context.Context, userId string, bookmarkId string) error {
	ret := _m.Called(ctx, userId, bookmarkId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userId, bookmarkId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarksByUserId provides a mock function with given fields: ctx, userId, limit, offset, sort
func (_m *BookmarkRepository) GetBookmarksByUserId(ctx context.Context, userId string, limit int, offset int, sort string) ([]*entity.Bookmark, int64, error) {
	ret := _m.Called(ctx, userId, limit, offset, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarksByUserId")
	}

	var r0 []*entity.Bookmark
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) ([]*entity.Bookmark, int64, error)); ok {
		return rf(ctx, userId, limit, offset, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) []*entity.Bookmark); ok {
		r0 = rf(ctx, userId, limit, offset, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, string) int64); ok {
		r1 = rf(ctx, userId, limit, offset, sort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, string) error); ok {
		r2 = rf(ctx, userId, limit, offset, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateBookmark provides a mock function with given fields: ctx, userId, bookmarkId, url, description
func (_m *BookmarkRepository) UpdateBookmark(ctx context.Context, userId string, bookmarkId string, url string, description string) error {
	ret := _m.Called(ctx, userId, bookmarkId, url, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userId, bookmarkId, url, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookmarkRepository creates a new instance of BookmarkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkRepository {
	mock := &BookmarkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
