// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_health_check

import (
	service "github.com/homework/lab/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheck is an autogenerated mock type for the HealthCheck type
type HealthCheck struct {
	mock.Mock
}

// Ping provides a mock function with no fields
func (_m *HealthCheck) Ping() (service.HealthStatusResult, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 service.HealthStatusResult
	var r1 error
	if rf, ok := ret.Get(0).(func() (service.HealthStatusResult, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() service.HealthStatusResult); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(service.HealthStatusResult)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthCheck creates a new instance of HealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheck {
	mock := &HealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
