// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShorternUrl is an autogenerated mock type for the ShorternUrl type
type ShorternUrl struct {
	mock.Mock
}

// ShortenUrlShortenUrl provides a mock function with given fields: ctx, url, exp
func (_m *ShorternUrl) ShortenUrlShortenUrl(ctx context.Context, url string, exp int64) (string, error) {
	ret := _m.Called(ctx, url, exp)

	if len(ret) == 0 {
		panic("no return value specified for ShortenUrlShortenUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return rf(ctx, url, exp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, url, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, url, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShorternUrl creates a new instance of ShorternUrl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShorternUrl(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShorternUrl {
	mock := &ShorternUrl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
