// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/homework/lab/internal/models/dto/api/user"
	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// Register provides a mock function with given fields: ctx, regiterInput
func (_m *UserService) Register(ctx context.Context, regiterInput user.UserRegister) (*user.UserInfo, error) {
	ret := _m.Called(ctx, regiterInput)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *user.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.UserRegister) (*user.UserInfo, error)); ok {
		return rf(ctx, regiterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.UserRegister) *user.UserInfo); ok {
		r0 = rf(ctx, regiterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.UserRegister) error); ok {
		r1 = rf(ctx, regiterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
