// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	api "github.com/homework/lab/internal/models/dto/api"
	bookmark_model "github.com/homework/lab/internal/models/dto/api/bookmark"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BookmarkService is an autogenerated mock type for the BookmarkService type
type BookmarkService struct {
	mock.Mock
}

// DeleteBookmark provides a mock function with given fields: ctx, userId, bookmarkId
func (_m *BookmarkService) DeleteBookmark(ctx context.Context, userId string, bookmarkId string) error {
	ret := _m.Called(ctx, userId, bookmarkId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userId, bookmarkId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarks provides a mock function with given fields: ctx, userId, query
func (_m *BookmarkService) GetBookmarks(ctx context.Context, userId string, query *bookmark_model.GetBookmarksQuery) (*api.PaginatedResponse[bookmark_model.BookmarkInfo], error) {
	ret := _m.Called(ctx, userId, query)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarks")
	}

	var r0 *api.PaginatedResponse[bookmark_model.BookmarkInfo]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *bookmark_model.GetBookmarksQuery) (*api.PaginatedResponse[bookmark_model.BookmarkInfo], error)); ok {
		return rf(ctx, userId, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *bookmark_model.GetBookmarksQuery) *api.PaginatedResponse[bookmark_model.BookmarkInfo]); ok {
		r0 = rf(ctx, userId, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PaginatedResponse[bookmark_model.BookmarkInfo])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *bookmark_model.GetBookmarksQuery) error); ok {
		r1 = rf(ctx, userId, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookmark provides a mock function with given fields: ctx, userId, bookmark
func (_m *BookmarkService) NewBookmark(ctx context.Context, userId string, bookmark *bookmark_model.NewBookmarkRequest) (*bookmark_model.BookmarkInfo, error) {
	ret := _m.Called(ctx, userId, bookmark)

	if len(ret) == 0 {
		panic("no return value specified for NewBookmark")
	}

	var r0 *bookmark_model.BookmarkInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *bookmark_model.NewBookmarkRequest) (*bookmark_model.BookmarkInfo, error)); ok {
		return rf(ctx, userId, bookmark)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *bookmark_model.NewBookmarkRequest) *bookmark_model.BookmarkInfo); ok {
		r0 = rf(ctx, userId, bookmark)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookmark_model.BookmarkInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *bookmark_model.NewBookmarkRequest) error); ok {
		r1 = rf(ctx, userId, bookmark)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookmark provides a mock function with given fields: ctx, request, userId, bookmarkId
func (_m *BookmarkService) UpdateBookmark(ctx context.Context, request *bookmark_model.UpdateBookmarkRequest, userId string, bookmarkId string) error {
	ret := _m.Called(ctx, request, userId, bookmarkId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bookmark_model.UpdateBookmarkRequest, string, string) error); ok {
		r0 = rf(ctx, request, userId, bookmarkId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookmarkService creates a new instance of BookmarkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkService {
	mock := &BookmarkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
