basePath: /
definitions:
  github_com_homework_lab_internal_models_dto_api.Response-github_com_homework_lab_internal_models_dto_api_user_UserInfo:
    properties:
      data:
        $ref: '#/definitions/github_com_homework_lab_internal_models_dto_api_user.UserInfo'
      message:
        type: string
    type: object
  github_com_homework_lab_internal_models_dto_api_user.UserInfo:
    properties:
      created_at:
        type: string
      display_name:
        type: string
      email:
        type: string
      id:
        type: string
      updated_at:
        type: string
      userName:
        type: string
    type: object
  github_com_homework_lab_internal_models_dto_api_user.UserRegister:
    properties:
      display_name:
        type: string
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - display_name
    - username
    type: object
  internal_handler_health_check.HealthResponse:
    properties:
      instance_id:
        type: string
      message:
        type: string
      service_name:
        type: string
    type: object
  internal_handler_shorten.shortenInputBody:
    properties:
      exp:
        maximum: 604800
        type: integer
      url:
        type: string
    required:
    - exp
    - url
    type: object
  internal_handler_shorten.shortenResMessage:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a book API
  title: Book API
  version: "1.0"
paths:
  /health-check:
    get:
      description: Check the health of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_health_check.HealthResponse'
      summary: Health check endpoint
      tags:
      - health_check
  /v1/links/redirect/{code}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Shorten code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
      tags:
      - link
  /v1/links/shorten:
    post:
      consumes:
      - application/json
      description: Generate shorten url based on original url that last upto 7 days
      parameters:
      - description: Input required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler_shorten.shortenInputBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_shorten.shortenResMessage'
      summary: Generate shorten url based on original url that last upto 7 days
      tags:
      - link
  /v1/users/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Input required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_homework_lab_internal_models_dto_api_user.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_homework_lab_internal_models_dto_api.Response-github_com_homework_lab_internal_models_dto_api_user_UserInfo'
      summary: Register user
      tags:
      - user
swagger: "2.0"
