name: cd-pipeline
on:
    workflow_run:
        workflows: ["ci-pipeline"]
        types:
            - completed
jobs:
    cd_pipeline_bookmark_service:
        if: |
            github.event.workflow_run.event == 'push' &&
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch != 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Run native SSH with sshpass
              run: |
                  sudo apt-get update && sudo apt-get install -y sshpass
                  sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'Connected via sshpass'"

            - name: Run deploy 
              working-directory: 
              run: |
                cd /app/golang-deployment
                git fetch
                git checkout test
                git pull origin test
                cd deployment
                docker ps -f "name=bookmark_service" --format '{{.Names}}' | grep -q bookmark_service && docker rm -f bookmark_service
                docker compose pull bookmark_service
                docker compose up -d
                docker system prune -f
